package view;

import DAO.MovieDAO;
import DAO.MusicDAO;
import DAO.TvDAO;
import Model.BoxSet;
import Model.Media;
import Model.Movie;
import Model.Music;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo
 */
public class MediaListView extends javax.swing.JFrame {

    List<Object> mediaList = new ArrayList<Object>();

       public MediaListView() {
        initComponents();
        createMediaList();

    }

    public void createMediaList() {

        createMediaList(null);

    }

    public void createMediaList(Media mediaSearch) {

        // *** Here is going to print out the medias on the view ***
        /* *** Here is going to search the media by title, then it is going 
        to list it on the view *** */
        DefaultTableModel content = (DefaultTableModel) jTableMedia.getModel();
        
        // *** Movie list ***
        content.setRowCount(0);
        List<Movie> movieList = MovieDAO.list();
        for (Movie m : movieList) {
            Object[] row = {
                m.getIdMedia(),
                m.getTitle(),
                m.getYearOfRelease(),
                m.getMediaFormat(),
                m.getAvailability(),
               //m.getPlanType().getPlanName(),
                m.getPrice(),
                m.getDescription(),};
            content.addRow(row);
            mediaList.add(m);
        }
        // *** Music list ***
        List<Music> musicList = MusicDAO.list();
        for (Music m : musicList) {
            Object[] row = {
                m.getIdMedia(),
                m.getTitle(),
                m.getYearOfRelease(),
                m.getMediaFormat(),
                m.getAvailability(),
                //m.getPlanType().getPlanName(),
                m.getPrice(),
                m.getDescription(),};
            content.addRow(row);
            mediaList.add(m);
        }
        // *** TV list ***
        List<BoxSet> tvList = TvDAO.list();
        for (BoxSet bs : tvList) {
            Object[] row = {
                bs.getIdMedia(),
                bs.getTitle(),
                bs.getYearOfRelease(),
                bs.getMediaFormat(),
                bs.getAvailability(),
                //m.getPlanType().getPlanName(),
                bs.getPrice(),
                bs.getDescription(),};
            content.addRow(row);
            mediaList.add(bs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedia = new javax.swing.JTable();
        jLSearch = new javax.swing.JLabel();
        jTextSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBClose = new javax.swing.JButton();
        jBOk = new javax.swing.JButton();
        jBEdit = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("*** Ultra-Vision Rental Media ***");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MEDIA LIST"));

        jTableMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Media:", "Title", "Year of Release:", "Price:", "Rented of days:", "Avaiability:", "Media Format:", "Description:", "Director/Studio/Band:"
            }
        ));
        jScrollPane1.setViewportView(jTableMedia);

        jLSearch.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLSearch.setText("Search of Title or ID:");

        jTextSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextSearchKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon_film.png"))); // NOI18N

        jBClose.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jBClose.setText("Close");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        jBOk.setText("OK");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        jBEdit.setText("Edit");
        jBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditActionPerformed(evt);
            }
        });

        jBDelete.setText("Delete");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBOk))
                            .addComponent(jLSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBClose, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBDelete)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBOk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEdit)
                    .addComponent(jBDelete))
                .addGap(40, 40, 40)
                .addComponent(jBClose)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jTextSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSearchKeyPressed
        // TODO add your handling code here:

        // *** Here is going to active the enter on the keyboard ***
        if (evt.getKeyCode() == 13) {
            jTextSearchActionPerformed(null);
        }

    }//GEN-LAST:event_jTextSearchKeyPressed

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        // TODO add your handling code here:

        // *** Her is calling the loadData method *** 
        loadData();
    }//GEN-LAST:event_jBOkActionPerformed

    private void jTextSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSearchKeyReleased
        // TODO add your handling code here:
        
        // *** Here is going to refresh the the list ***
        if (jTextSearch.getText().isEmpty()) {
            loadData();
        }
    }

    public void loadData() {

        // *** Search mediaList ***
        Media mediaSearch = new Media();

        try {
            int idMedia = Integer.parseInt(jTextSearch.getText());
            mediaSearch.setIdMedia(String.valueOf(idMedia));

        } catch (Exception e) {

        }

        mediaSearch.setTitle(jTextSearch.getText());

        createMediaList(mediaSearch);
    }//GEN-LAST:event_jTextSearchKeyReleased

    private void jBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditActionPerformed
        // TODO add your handling code here:

        // *** Update process ***
        
        // *** Select the row to edit ***
        int row = jTableMedia.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "select a row ");
        } else {
            Object media = this.mediaList.get(row);

            //*** Sent to the edit clientsList page ***
            NewMediaView editPage = new NewMediaView(this);
            if (media.getClass() == Movie.class) {
                editPage.setMovie((Movie) media);
            }
            if (media.getClass() == Music.class) {
                editPage.setMusic((Music) media);
            }
            if (media.getClass() == BoxSet.class) {
                editPage.setBoxSet((BoxSet) media);
            }

            editPage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            editPage.setVisible(true);
        }

    }//GEN-LAST:event_jBEditActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:

        //*** Delete data process *** 
        // *** Check if any row was selected. ***
        int row = jTableMedia.getSelectedRow();
        if (row > -1) {
            Object media = mediaList.get(row);
            int option = JOptionPane
                    .showConfirmDialog(this, "Do you want to delete",
                            "data deleted confirmation", JOptionPane.YES_NO_OPTION);

            // *** Here is going to get the idMedia and delete it from the database. ***
            if (option == JOptionPane.YES_OPTION) {
                if (media.getClass() == Movie.class) {
                    if (MovieDAO.delete(Integer.parseInt(((Movie) media).getIdMedia()))) {

                        JOptionPane.showMessageDialog(this, "Deleted ");

                        // *** update the list ***
                        createMediaList();
                    } else {

                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
                if (media.getClass() == Music.class) {
                    if (MusicDAO.delete(Integer.parseInt(((Music) media).getIdMedia()))) {

                        JOptionPane.showMessageDialog(this, "Deleted ");

                        // *** Update the list ***
                        createMediaList();

                    } else {
                        JOptionPane.showMessageDialog(this, "Error");

                    }
                }
                if (media.getClass() == BoxSet.class) {
                    if (TvDAO.delete(Integer.parseInt(((BoxSet) media).getIdMedia()))) {

                        JOptionPane.showMessageDialog(this, "Deleted ");

                        // *** Update the list ***
                        createMediaList();

                    } else {
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }

            }
        } else {

            JOptionPane.showConfirmDialog(this, "Select a row to delete");
        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        // TODO add your handling code here:
        
        // *** Close the register client window without close the program.
        dispose();
        
    }//GEN-LAST:event_jBCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediaListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediaListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediaListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediaListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MediaListView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBEdit;
    private javax.swing.JButton jBOk;
    private javax.swing.JLabel jLSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedia;
    private javax.swing.JTextField jTextSearch;
    // End of variables declaration//GEN-END:variables

}

// *** REFERENCES: ***
/* Linguagem Tecnica de Programação - Marcelo Santos.
Portal Ceilanda, cursos. https://marcelo.portalceilandia.com.br/site/ltp1/*/
