package view;

import DAO.ClientDAO;
import DAO.MovieDAO;
import DAO.MusicDAO;
import DAO.TvDAO;
import Model.BoxSet;
import Model.Media;
import controller.MediaRegister;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Model.MediaFormat;
import Model.MediaType;
import Model.Movie;
import Model.Music;
import Model.PlanType;

/**
 *
 * @author Marcelo
 */
public class NewMediaView extends javax.swing.JFrame {

    private Media media = new Media();
    private MediaListView mediaList;
    // private final RentProcessView clientDetails;

    // *** Here is going to bring all clients details to the rent page. ***
    public void setMusic(Music music) {
        this.media = music;
        jTextTitle.setText(music.getTitle());
        jTextComplement.setText(music.getBand());
        jTextYear.setText(String.valueOf(music.getYearOfRelease()));
        jTextPrice.setText(String.valueOf(music.getPrice()));

        //goupButton code:
        String mF = music.getMediaFormat().toUpperCase();
        System.out.println("stop here " + mF);

        switch (mF) {
            case "CD":
                jRadioBCd.setSelected(true);
                break;
            case "DVD":
                jRadioBDvd.setSelected(true);
                break;
            case "BLUERAY":
                jRadioBBlueray.setSelected(true);
                break;
        }
        
        

        jTextidMedia.setVisible(true);
        jTextidMedia.setEditable(false);
        jLidMedia.setVisible(true);
        jTextidMedia.setText(music.getIdMedia());
        jRadioBMusic.setVisible(true);
        jRadioBMusic.setSelected(true);
    }
     public void setMovie(Movie movie) {
        this.media = movie;
        jTextTitle.setText(movie.getTitle());
        jTextComplement.setText(movie.getDirector());
        jTextYear.setText(String.valueOf(movie.getYearOfRelease()));
        jTextPrice.setText(String.valueOf(movie.getPrice()));

        //goupButton code:
        String mF = movie.getMediaFormat().toUpperCase();
        System.out.println("stop here " + mF);

        switch (mF) {
            case "CD":
                jRadioBCd.setSelected(true);
                break;
            case "DVD":
                jRadioBDvd.setSelected(true);
                break;
            case "BLUERAY":
                jRadioBBlueray.setSelected(true);
                break;
        }
        
        jLComplement.setText("Director");
        

        jTextidMedia.setVisible(true);
        jTextidMedia.setEditable(false);
        jLidMedia.setVisible(true);
        jTextidMedia.setText(movie.getIdMedia());
        jRadioBMovie.setVisible(true);
        jRadioBMovie.setSelected(true);
    }
      public void setBoxSet(BoxSet tv) {
        this.media = tv;
        jTextTitle.setText(tv.getTitle());
        jTextComplement.setText(tv.getStudio());
        jTextYear.setText(String.valueOf(tv.getYearOfRelease()));
        jTextPrice.setText(String.valueOf(tv.getPrice()));

        //goupButton code:
        String mF = tv.getMediaFormat().toUpperCase();
        System.out.println("stop here " + mF);

        switch (mF) {
            case "CD":
                jRadioBCd.setSelected(true);
                break;
            case "DVD":
                jRadioBDvd.setSelected(true);
                break;
            case "BLUERAY":
                jRadioBBlueray.setSelected(true);
                break;
        }
        
        jLComplement.setText("Studio");

        jTextidMedia.setVisible(true);
        jTextidMedia.setEditable(false);
        jLidMedia.setVisible(true);
        jTextidMedia.setText(tv.getIdMedia());
        jRadioBTv.setVisible(true);
        jRadioBTv.setSelected(true);
    }

    /**
     * Creates new form RentProcessView
     */
    public NewMediaView(MediaListView mediaList) {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        initComponents();
        jTextidMedia.setVisible(true);
        jTextidMedia.setEditable(false);
        jLidMedia.setVisible(true);
        jRadioBMusic.setVisible(false);
        jRadioBMovie.setVisible(false);
        jRadioBTv.setVisible(false);
        this.mediaList = mediaList;
    }

    /**
     * Creates new form MediaItens
     */
    public NewMediaView() {
        initComponents();
        jRadioBMusic.setSelected(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        buttonGroupMediaF = new javax.swing.ButtonGroup();
        buttonGroupT = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLidMedia = new javax.swing.JLabel();
        jTextidMedia = new javax.swing.JTextField();
        jLTitle = new javax.swing.JLabel();
        jLYear = new javax.swing.JLabel();
        jLMediaF = new javax.swing.JLabel();
        jTextTitle = new javax.swing.JTextField();
        jTextYear = new javax.swing.JTextField();
        jLPrice = new javax.swing.JLabel();
        jTextPrice = new javax.swing.JTextField();
        jLComplement = new javax.swing.JLabel();
        jTextComplement = new javax.swing.JTextField();
        jLDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLAvailability = new javax.swing.JLabel();
        jTextAvailability = new javax.swing.JTextField();
        jBSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioBDvd = new javax.swing.JRadioButton();
        jRadioBCd = new javax.swing.JRadioButton();
        jRadioBBlueray = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jRadioBMusic = new javax.swing.JRadioButton();
        jRadioBTv = new javax.swing.JRadioButton();
        jRadioBMovie = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("*** Ultra-Vision Media ***");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("NEW MEDIA"));

        jLidMedia.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLidMedia.setText("ID Media: ");

        jTextidMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextidMediaActionPerformed(evt);
            }
        });

        jLTitle.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLTitle.setText("Title: ");

        jLYear.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLYear.setText("Year of Release:");

        jLMediaF.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLMediaF.setText("Media Format:");

        jLPrice.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLPrice.setText("Price:");

        jTextPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPriceActionPerformed(evt);
            }
        });

        jLComplement.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLComplement.setText("Band: ");

        jTextComplement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextComplementActionPerformed(evt);
            }
        });

        jLDescription.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLDescription.setText("Description:");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jLAvailability.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLAvailability.setText("Availability:");

        jBSave.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jBSave.setText("Save");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonGroupMediaF.add(jRadioBDvd);
        jRadioBDvd.setText("DVD");

        buttonGroupMediaF.add(jRadioBCd);
        jRadioBCd.setText("CD");

        buttonGroupMediaF.add(jRadioBBlueray);
        jRadioBBlueray.setText("BLUERAY");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setText("Media Type: ");

        buttonGroupT.add(jRadioBMusic);
        jRadioBMusic.setText("Music");
        jRadioBMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBMusicActionPerformed(evt);
            }
        });

        buttonGroupT.add(jRadioBTv);
        jRadioBTv.setText("TV");
        jRadioBTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBTvActionPerformed(evt);
            }
        });

        buttonGroupT.add(jRadioBMovie);
        jRadioBMovie.setText("Movie");
        jRadioBMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLComplement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jTextComplement)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLYear)
                                .addGap(12, 12, 12)
                                .addComponent(jTextYear))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLMediaF)
                                        .addGap(196, 196, 196)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLidMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextidMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioBMusic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioBTv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioBMovie))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioBDvd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioBCd)
                                        .addGap(16, 16, 16)
                                        .addComponent(jRadioBBlueray)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jBSave))
                        .addComponent(jLDescription)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLAvailability))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextPrice)
                                .addComponent(jTextAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLidMedia)
                                    .addComponent(jTextidMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLTitle)
                                    .addComponent(jTextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLComplement)
                                    .addComponent(jTextComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLYear)
                                    .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jLMediaF)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioBDvd)
                                    .addComponent(jRadioBCd)
                                    .addComponent(jRadioBBlueray))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioBMusic)
                                    .addComponent(jRadioBTv)
                                    .addComponent(jRadioBMovie)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPrice)
                            .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBSave)))
                .addContainerGap())
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextidMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextidMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextidMediaActionPerformed

    private void jTextPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPriceActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        // TODO add your handling code here:
        //Here is gonna save the medias details
        if (media.getIdMedia() == null) {
            if (jRadioBMovie.isSelected()) {
                media = new Movie();
            }
             if (jRadioBMusic.isSelected()) {
                media = new Music();
            }
              if (jRadioBTv.isSelected()) {
                media = new BoxSet();
            }
        }
        media.setTitle(jTextTitle.getText());
        //media.setDirector(jTextDirector.getText());

        //media.setBand(jTextBand.getText());
        //media.setStudio(jTextStudio.getText());
        media.setYearOfRelease(Integer.parseInt(jTextYear.getText()));
        //media.setMediaFormat(buttonGroupMediaF.getSelection());
        media.setPrice(Float.parseFloat(jTextPrice.getText()));

        
        if ( jRadioBMusic.isSelected()) { 
            media.setMediaType(MediaType.MUSIC.name());
        }else if (jRadioBTv.isSelected()) {
            media.setMediaType(MediaType.TV.name());
        }else if (jRadioBMovie.isSelected()) {
           media.setMediaType(MediaType.MOVIE.name());
        }else{
            JOptionPane.showMessageDialog(this, "Select a Media Type");
            return;
        }
        // Here is to show up the media format selected on the edit page.
        if (jRadioBCd.isSelected()) {
            media.setMediaFormat(MediaFormat.CD.name());
        }else if(jRadioBDvd.isSelected()){
            media.setMediaFormat(MediaFormat.DVD.name());
        }else if(jRadioBBlueray.isSelected()){
            media.setMediaFormat(MediaFormat.BLUERAY.name());
         }else{
            
            JOptionPane.showMessageDialog(this, "Select a Media Format");
            return;
        }
        
         /* *** save process *** vai verificar o tipo de midia e da acordo com o tipo de 
         media vai inserir ou alterar */
         
            String msg = "Media was registed";
            boolean sucess = false;
            if (media.getIdMedia()== null) {
                if(media.getMediaType().equals(MediaType.MUSIC.name())){
                  Music music = (Music)media;          
                    music.setBand(jTextComplement.getText());
                   sucess =  MusicDAO.insert(music);
                }
                if(media.getMediaType().equals(MediaType.MOVIE.name())){
                  Movie movie = (Movie)media;          
                    movie.setDirector(jTextComplement.getText());
                   sucess =  MovieDAO.insert(movie);
                }
                if(media.getMediaType().equals(MediaType.TV.name())){
                  BoxSet tv = (BoxSet)media;          
                    tv.setStudio(jTextComplement.getText());
                   sucess =  TvDAO.insert(tv);
                }
            }else{
                if(media.getMediaType().equals(MediaType.MUSIC.name())){
                  Music music = (Music)media;          
                  music.setBand(jTextComplement.getText());
                  sucess = MusicDAO.update(music);
                }
                if(media.getMediaType().equals(MediaType.MOVIE.name())){
                  Movie movie = (Movie)media;          
                    movie.setDirector(jTextComplement.getText());
                   sucess =  MovieDAO.update(movie);
                }
                if(media.getMediaType().equals(MediaType.TV.name())){
                  BoxSet tv = (BoxSet)media;          
                    tv.setStudio(jTextComplement.getText());
                   sucess =  TvDAO.update(tv);
                }
                
                 msg = "Media was updated";
            }
            
            if (sucess) {
                JOptionPane.showMessageDialog(this, msg);
                
                if (mediaList != null) {
                   mediaList.createMediaList();
                }
                dispose();
                
            }else{
                JOptionPane.showMessageDialog(this, "Error in register a media");
            }
               
        
         
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jTextComplementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextComplementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextComplementActionPerformed

    private void jRadioBMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBMusicActionPerformed
        // TODO add your handling code here:
        jLComplement.setText("Band:");
    }//GEN-LAST:event_jRadioBMusicActionPerformed

    private void jRadioBTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBTvActionPerformed
        // TODO add your handling code here:
         jLComplement.setText("Studio:");
    }//GEN-LAST:event_jRadioBTvActionPerformed

    private void jRadioBMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBMovieActionPerformed
        // TODO add your handling code here:
         jLComplement.setText("Director:");
    }//GEN-LAST:event_jRadioBMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMediaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMediaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMediaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMediaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMediaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMediaF;
    private javax.swing.ButtonGroup buttonGroupT;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLAvailability;
    private javax.swing.JLabel jLComplement;
    private javax.swing.JLabel jLDescription;
    private javax.swing.JLabel jLMediaF;
    private javax.swing.JLabel jLPrice;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JLabel jLYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLidMedia;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioBBlueray;
    private javax.swing.JRadioButton jRadioBCd;
    private javax.swing.JRadioButton jRadioBDvd;
    private javax.swing.JRadioButton jRadioBMovie;
    private javax.swing.JRadioButton jRadioBMusic;
    private javax.swing.JRadioButton jRadioBTv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextAvailability;
    private javax.swing.JTextField jTextComplement;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextTitle;
    private javax.swing.JTextField jTextYear;
    private javax.swing.JTextField jTextidMedia;
    // End of variables declaration//GEN-END:variables
}
